#!/usr/local/env groovy

/*
  Provision terraform webapp
*/

pipeline {
    agent any

    parameters {
        choice(
            choices: ['us-east-1','sa-east-1'],
            description: 'Amazon region',
            name: 'REGION')
        choice(
            choices: ['develop','staging','production'],
            description: 'Envirnonment',
            name: 'TIER')
    }

    environment {
        BACKEND_KEY = "webapp"
    }

    stages {
        stage('dependencies') {
            steps {
                sh """
                apt-get install unzip -y
                curl -sSL https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip -o packer.zip
                unzip packer.zip
                """
            }
        }
    }

    stages {
        stage('validate') {
            steps {
                checkout scm
                withAWS(role:"role-instance-jenkins", roleAccount:"$AWS_ACCOUNT_ID", roleSessionName: "jenkins-$env.TIER") {
                    sh """
                    packer validate -var "tier=${TIER}" webapp.json
                    """
                }
            }
        }

        stage('build') {
            steps {
                withAWS(role:"role-instance-jenkins", roleAccount:"$ACCOUNT_AWS_ID", roleSessionName: "jenkins-$TIER") {
                    sh """
                    packer build -var "tier=${TIER}"
                    """
                }
            }
        }
    }
}