---
- name: default web server php
  template:
    src: php/default.yml.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  when: enable_web_server_php
  notify: restarted nginx service

- name: enable default web server
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: enable_web_server_php
