---
- hosts: all
  become: yes

  pre_tasks:
    - name: update cache
      shell: apt-get update -y
    - name: install the required package
      apt:
        name: ['ansible','python3-pip']
        state: present
        update_cache: yes

  roles:
    - nginx